name: Build & Publish Termux APK

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Fix submodule paths
      run: |
        # Создаем необходимые симлинки для корректной работы сборки
        mkdir -p Submodule/AIDE/app_rewrite/libs
        ln -sf $GITHUB_WORKSPACE/Submodule/AIDE/AIDE-Plus/app_rewrite/libs/prefab-plugin-2.1.0.jar Submodule/AIDE/app_rewrite/libs/
        ln -sf $GITHUB_WORKSPACE/Submodule/AIDE/AIDE-Plus/app_rewrite/libs/android.jar Submodule/AIDE/app_rewrite/libs/
        
        # Проверяем существование ключевых файлов
        if [ ! -f "Submodule/AIDE/app_rewrite/libs/prefab-plugin-2.1.0.jar" ]; then
          echo "Error: prefab-plugin-2.1.0.jar not found!"
          exit 1
        fi

    - name: Fix XML dependencies in aaptcompiler
      run: |
        # Проверяем путь к файлу сборки aaptcompiler
        XML_GRADLE_FILE="$GITHUB_WORKSPACE/Submodule/Compiletion/Xml/aaptcompiler/build.gradle.kts"
        
        if [ -f "$XML_GRADLE_FILE" ]; then
          echo "Adding XML dependencies to $XML_GRADLE_FILE"
          
          # Простой способ добавления зависимостей
          if grep -q "dependencies" "$XML_GRADLE_FILE"; then
            # Если блок dependencies уже есть, добавляем зависимости в него
            cp "$XML_GRADLE_FILE" "$XML_GRADLE_FILE.bak"
            awk 'BEGIN {found=0} 
            /dependencies[\s]*\{/ {found=1; print; print "    implementation(\"javax.xml.stream:stax-api:1.0-2\")"; print "    implementation(\"com.sun.xml.parsers:jaxp-ri:1.4.5\")"; print "    implementation(\"org.codehaus.woodstox:woodstox-core-asl:4.4.1\")"; next} 
            {print}' "$XML_GRADLE_FILE.bak" > "$XML_GRADLE_FILE"
          else
            # Если блока dependencies нет, добавляем в конец файла
            echo -e "\ndependencies {\n    implementation(\"javax.xml.stream:stax-api:1.0-2\")\n    implementation(\"com.sun.xml.parsers:jaxp-ri:1.4.5\")\n    implementation(\"org.codehaus.woodstox:woodstox-core-asl:4.4.1\")\n}" >> "$XML_GRADLE_FILE"
          fi
          
          echo "Updated $XML_GRADLE_FILE:"
          cat "$XML_GRADLE_FILE"
        else
          echo "WARNING: aaptcompiler build.gradle.kts not found at $XML_GRADLE_FILE"
          find "$GITHUB_WORKSPACE" -name "aaptcompiler" -type d || true
        fi

    - name: Build APK for termux
      run: |
        ./gradlew clean
        ./gradlew :app_flavor:termux:assembleRelease --stacktrace --info

    - name: Get version info
      id: version
      run: |
        VERSION=$(grep -m 1 "versionName" app_flavor/termux/build.gradle | awk '{print $2}' | tr -d '"')
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "APK_NAME=AIDE-Plus-Termux-v${VERSION}.apk" >> $GITHUB_ENV

    - name: Rename and move APK
      run: |
        mkdir -p build/outputs/apk/
        # Check if APK exists at expected location
        if [ -f "app_flavor/termux/build/outputs/apk/termux/release/app-termux-release.apk" ]; then
          mv app_flavor/termux/build/outputs/apk/termux/release/app-termux-release.apk build/outputs/apk/${APK_NAME}
          echo "APK successfully renamed and moved to build/outputs/apk/${APK_NAME}"
        else
          echo "WARNING: APK not found at expected location"
          # Find any APK files
          find "$GITHUB_WORKSPACE" -name "*.apk" -type f
          exit 1
        fi
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: AIDE-Plus-Termux-APK
        path: build/outputs/apk/${APK_NAME}
        
    - name: Setup GitHub Pages
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/outputs/apk/
        
    - name: Deploy to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/deploy-pages@v4
