name: Build & Publish Release APK

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [ default, termux ]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Ensure mavenCentral is in all build.gradle(.kts)
      run: |
        find . -type f \( -name "build.gradle.kts" -o -name "build.gradle" \) | while read file; do
          grep -q 'mavenCentral()' "$file" || \
            sed -i '/repositories\s*{/a \    mavenCentral()' "$file"
        done

    - name: Ensure mavenCentral is in dependencyResolutionManagement (settings.gradle.kts)
      run: |
        if [ -f "settings.gradle.kts" ]; then
          grep -q 'mavenCentral()' settings.gradle.kts || \
            sed -i '/repositories\s*{/a \        mavenCentral()' settings.gradle.kts
        fi

    - name: Patch gradle/libs.versions.toml for XML dependencies
      run: |
        FILE="gradle/libs.versions.toml"
        # Ensure [versions] exists and add versions if not present
        if ! grep -q '^\[versions\]' "$FILE"; then
          echo '[versions]' | cat - "$FILE" > temp && mv temp "$FILE"
        fi
        grep -q '^woodstox-core[ ]*=' "$FILE" || sed -i '/^\[versions\]/a woodstox-core = "6.2.4"' "$FILE"
        grep -q '^stax-api[ ]*=' "$FILE" || sed -i '/^\[versions\]/a stax-api = "1.0-2"' "$FILE"
        # Ensure [libraries] exists and add libraries if not present
        if ! grep -q '^\[libraries\]' "$FILE"; then
          echo '[libraries]' >> "$FILE"
        fi
        grep -q '^woodstox-core[ ]*=' "$FILE" || sed -i '/^\[libraries\]/a woodstox-core = { module = "org.codehaus.woodstox:woodstox-core", version.ref = "woodstox-core" }' "$FILE"
        grep -q '^stax-api[ ]*=' "$FILE" || sed -i '/^\[libraries\]/a stax-api = { module = "javax.xml.stream:stax-api", version.ref = "stax-api" }' "$FILE"
        echo "----- gradle/libs.versions.toml -----"
        cat "$FILE"
    
    - name: Patch aaptcompiler build.gradle.kts for XML dependencies
      run: |
        FILE="Submodule/Compiletion/Xml/aaptcompiler/build.gradle.kts"
        # Удаляем блок repositories если он есть (только верхний уровень!)
        sed -i '/^repositories\s*{/,/^}/d' "$FILE"
        # Добавляем зависимости если их нет
        grep -q 'javax.xml.stream:stax-api' "$FILE" || \
          sed -i '/dependencies\s*{/a \    implementation("javax.xml.stream:stax-api:1.0-2")' "$FILE"
        grep -q 'org.codehaus.woodstox:woodstox-core' "$FILE" || \
          sed -i '/dependencies\s*{/a \    implementation("org.codehaus.woodstox:woodstox-core:6.2.4")' "$FILE"
        echo "----- $FILE -----"
        cat "$FILE"
        
    - name: Workaround for prefab-plugin path issue (for all flavors)
      run: |
        ACTUAL_FILE_LOCATION="$GITHUB_WORKSPACE/Submodule/AIDE/AIDE-Plus/app_rewrite/libs/prefab-plugin-2.1.0.jar"
        EXPECTED_SYMLINK_DIR="$GITHUB_WORKSPACE/Submodule/AIDE/app_rewrite/libs"
        EXPECTED_SYMLINK_PATH="$EXPECTED_SYMLINK_DIR/prefab-plugin-2.1.0.jar"
        if [ -f "$ACTUAL_FILE_LOCATION" ]; then
          mkdir -p "$EXPECTED_SYMLINK_DIR"
          ln -sf "$ACTUAL_FILE_LOCATION" "$EXPECTED_SYMLINK_PATH"
        fi

    - name: Build APK for ${{ matrix.flavor }}
      run: ./gradlew app_flavor:${{ matrix.flavor }}:assembleRelease

    - name: Get TAG_VERSION_NAME from build.gradle.kts
      id: get_version_info
      run: |
        TAG_VERSION_NAME=$(grep "val TAG_VERSION_NAME =" build.gradle.kts | awk '{print $4}' | tr -d '"')
        echo "TAG_VERSION_NAME=${TAG_VERSION_NAME}" >> $GITHUB_ENV

    - name: Rename APK for ${{ matrix.flavor }}
      run: mv build/app_flavor-${{ matrix.flavor }}/outputs/apk/${{ matrix.flavor }}/release/app-${{ matrix.flavor }}-release.apk build/app/outputs/apk/${{ matrix.flavor }}/release/AIDE-${{ matrix.flavor }}.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AIDE-${{ matrix.flavor }}.apk
        path: build/app/outputs/apk/${{ matrix.flavor }}/release/AIDE-${{ matrix.flavor }}.apk
